.include "include/beatscript.inc"

.section .scene

@ Script
script script_scene_flash_mem_test
    set_tempo 120
    pause_scene

    run func_08007324 TRUE
    scene_set_byte 8, TRUE
    pause_scene

    scene_set_byte 8, FALSE
    fade_music_out 12
    fade_screen_out 12, BLACK
    rest 12
    stop


@ Local Scene
struct sub_scene_flash_mem_test
    /* Start  */ .word flash_test_scene_start,  0
    /* Paused */ .word flash_test_scene_paused, 0
    /* Active */ .word flash_test_scene_update, 0
    /* Stop   */ .word flash_test_scene_stop,   0
    /* Script */ .word script_scene_flash_mem_test
endstruct

@ RIQ Flash Memory Test Scene
struct scene_flash_mem_test
    /* Start  */ .word func_0801d86c, sub_scene_flash_mem_test
    /* Update */ .word func_0801d8d8, 0
    /* Stop   */ .word NULL,          0
    /* Memory */ .word 0x10
endstruct

.end
