// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "remix_1_extra_prologue_anim_cells.inc.c"

struct Animation anim_remix_1_extra_prologue_title[] = {
    /* 000 */ { remix_1_extra_prologue_cel000, 40 },
    /* 001 */ { remix_1_extra_prologue_cel001, 6 },
    /* 002 */ { remix_1_extra_prologue_cel002, 6 },
    /* 003 */ { remix_1_extra_prologue_cel003, 6 },
    /* 004 */ { remix_1_extra_prologue_cel004, 6 },
    /* 005 */ { remix_1_extra_prologue_cel005, 6 },
    /* 006 */ { remix_1_extra_prologue_cel006, 6 },
    /* 007 */ { remix_1_extra_prologue_cel007, 100 },
    /* 008 */ END_ANIMATION,
};

