#pragma once

#include "global.h"
#include "graphics.h"

/* EPILOGUES - COMPRESSED GRAPHICS / PALETTES */

extern struct CompressedGraphics sneaky_spirits_epilogue_bg_tiles;
extern struct CompressedGraphics sneaky_spirits_epilogue_bg_map_superb;
extern struct CompressedGraphics sneaky_spirits_epilogue_bg_map_ok;
extern struct CompressedGraphics sneaky_spirits_epilogue_bg_map_try_again;
extern Palette epilogue_sneaky_spirits_bg_pal[];

extern struct CompressedGraphics spaceball_epilogue_bg_tiles;
extern struct CompressedGraphics spaceball_epilogue_bg_map_superb;
extern struct CompressedGraphics spaceball_epilogue_bg_map_ok;
extern struct CompressedGraphics spaceball_epilogue_bg_map_try_again;
extern Palette epilogue_spaceball_bg_pal[];

extern struct CompressedGraphics bon_dance_epilogue_bg_tiles;
extern struct CompressedGraphics bon_dance_epilogue_bg_map_superb;
extern struct CompressedGraphics bon_dance_epilogue_bg_map_ok;
extern struct CompressedGraphics bon_dance_epilogue_bg_map_try_again;
extern Palette epilogue_bon_dance_bg_pal[];

extern struct CompressedGraphics bon_odori_epilogue_bg_tiles;
extern struct CompressedGraphics bon_odori_epilogue_bg_map_superb;
extern struct CompressedGraphics bon_odori_epilogue_bg_map_ok;
extern struct CompressedGraphics bon_odori_epilogue_bg_map_try_again;
extern Palette epilogue_bon_odori_bg_pal[];

extern struct CompressedGraphics karate_man_epilogue_bg_tiles;
extern struct CompressedGraphics karate_man_epilogue_bg_map_superb;
extern struct CompressedGraphics karate_man_epilogue_bg_map_ok;
extern struct CompressedGraphics karate_man_epilogue_bg_map_try_again;
extern Palette epilogue_karate_man_bg_pal[];

extern struct CompressedGraphics cosmic_dance_epilogue_bg_tiles;
extern struct CompressedGraphics cosmic_dance_epilogue_bg_map_superb;
extern struct CompressedGraphics cosmic_dance_epilogue_bg_map_ok;
extern struct CompressedGraphics cosmic_dance_epilogue_bg_map_try_again;
extern Palette epilogue_cosmic_dance_bg_pal[];

extern struct CompressedGraphics drum_live_epilogue_bg_tiles;
extern struct CompressedGraphics drum_live_epilogue_bg_map_superb;
extern struct CompressedGraphics drum_live_epilogue_bg_map_ok;
extern struct CompressedGraphics drum_live_epilogue_bg_map_try_again;
extern Palette epilogue_drum_live_bg_pal[];

extern struct CompressedGraphics night_walk_epilogue_bg_tiles;
extern struct CompressedGraphics night_walk_epilogue_bg_map_superb;
extern struct CompressedGraphics night_walk_epilogue_bg_map_ok;
extern struct CompressedGraphics night_walk_epilogue_bg_map_try_again;
extern Palette epilogue_night_walk_bg_pal[];

extern struct CompressedGraphics showtime_epilogue_bg_tiles;
extern struct CompressedGraphics showtime_epilogue_bg_map_superb;
extern struct CompressedGraphics showtime_epilogue_bg_map_ok;
extern struct CompressedGraphics showtime_epilogue_bg_map_try_again;
extern Palette epilogue_showtime_bg_pal[];

extern struct CompressedGraphics bouncy_road_epilogue_bg_tiles;
extern struct CompressedGraphics bouncy_road_epilogue_bg_map_superb;
extern struct CompressedGraphics bouncy_road_epilogue_bg_map_ok;
extern struct CompressedGraphics bouncy_road_epilogue_bg_map_try_again;
extern Palette epilogue_bouncy_road_bg_pal[];

extern struct CompressedGraphics rhythm_tweezers_epilogue_bg_tiles;
extern struct CompressedGraphics rhythm_tweezers_epilogue_bg_map_superb;
extern struct CompressedGraphics rhythm_tweezers_epilogue_bg_map_ok;
extern struct CompressedGraphics rhythm_tweezers_epilogue_bg_map_try_again;
extern Palette epilogue_rhythm_tweezers_bg_pal[];

extern struct CompressedGraphics fireworks_epilogue_bg_tiles;
extern struct CompressedGraphics fireworks_epilogue_bg_map_superb;
extern struct CompressedGraphics fireworks_epilogue_bg_map_ok;
extern struct CompressedGraphics fireworks_epilogue_bg_map_try_again;
extern Palette epilogue_fireworks_bg_pal[];

extern struct CompressedGraphics clappy_trio_epilogue_bg_tiles;
extern struct CompressedGraphics clappy_trio_epilogue_bg_map_superb;
extern struct CompressedGraphics clappy_trio_epilogue_bg_map_ok;
extern struct CompressedGraphics clappy_trio_epilogue_bg_map_try_again;
extern Palette epilogue_clappy_trio_bg_pal[];

extern struct CompressedGraphics snappy_trio_epilogue_bg_tiles;
extern struct CompressedGraphics snappy_trio_epilogue_bg_map_superb;
extern struct CompressedGraphics snappy_trio_epilogue_bg_map_ok;
extern struct CompressedGraphics snappy_trio_epilogue_bg_map_try_again;
extern Palette epilogue_snappy_trio_bg_pal[];

extern struct CompressedGraphics samurai_slice_epilogue_bg_tiles;
extern struct CompressedGraphics samurai_slice_epilogue_bg_map_superb;
extern struct CompressedGraphics samurai_slice_epilogue_bg_map_ok;
extern struct CompressedGraphics samurai_slice_epilogue_bg_map_try_again;
extern Palette epilogue_samurai_slice_bg_pal[];

extern struct CompressedGraphics power_calligraphy_epilogue_bg_tiles;
extern struct CompressedGraphics power_calligraphy_epilogue_bg_map_superb;
extern struct CompressedGraphics power_calligraphy_epilogue_bg_map_ok;
extern struct CompressedGraphics power_calligraphy_epilogue_bg_map_try_again;
extern Palette epilogue_power_calligraphy_bg_pal[];

extern struct CompressedGraphics marching_orders_epilogue_bg_tiles;
extern struct CompressedGraphics marching_orders_epilogue_bg_map_superb;
extern struct CompressedGraphics marching_orders_epilogue_bg_map_ok;
extern struct CompressedGraphics marching_orders_epilogue_bg_map_try_again;
extern Palette epilogue_marching_orders_bg_pal[];

extern struct CompressedGraphics marching_orders_2_epilogue_bg_tiles;
extern struct CompressedGraphics marching_orders_2_epilogue_bg_map_superb;
extern struct CompressedGraphics marching_orders_2_epilogue_bg_map_ok;
extern struct CompressedGraphics marching_orders_2_epilogue_bg_map_try_again;
extern Palette epilogue_marching_orders_2_bg_pal[];

extern struct CompressedGraphics polyrhythm_epilogue_bg_tiles;
extern struct CompressedGraphics polyrhythm_epilogue_bg_map_superb;
extern struct CompressedGraphics polyrhythm_epilogue_bg_map_ok;
extern struct CompressedGraphics polyrhythm_epilogue_bg_map_try_again;
extern Palette epilogue_polyrhythm_bg_pal[];

extern struct CompressedGraphics quiz_show_epilogue_bg_tiles;
extern struct CompressedGraphics quiz_show_epilogue_bg_map_superb;
extern struct CompressedGraphics quiz_show_epilogue_bg_map_ok;
extern struct CompressedGraphics quiz_show_epilogue_bg_map_try_again;
extern Palette epilogue_quiz_show_bg_pal[];

extern struct CompressedGraphics bunny_hop_epilogue_bg_tiles;
extern struct CompressedGraphics bunny_hop_epilogue_bg_map_superb;
extern struct CompressedGraphics bunny_hop_epilogue_bg_map_ok;
extern struct CompressedGraphics bunny_hop_epilogue_bg_map_try_again;
extern Palette epilogue_bunny_hop_bg_pal[];

extern struct CompressedGraphics rap_men_epilogue_bg_tiles;
extern struct CompressedGraphics rap_men_epilogue_bg_map_superb;
extern struct CompressedGraphics rap_men_epilogue_bg_map_ok;
extern struct CompressedGraphics rap_men_epilogue_bg_map_try_again;
extern Palette epilogue_rap_men_bg_pal[];

extern struct CompressedGraphics rap_women_epilogue_bg_tiles;
extern struct CompressedGraphics rap_women_epilogue_bg_map_superb;
extern struct CompressedGraphics rap_women_epilogue_bg_map_ok;
extern struct CompressedGraphics rap_women_epilogue_bg_map_try_again;
extern Palette epilogue_rap_women_bg_pal[];

extern struct CompressedGraphics rat_race_epilogue_bg_tiles;
extern struct CompressedGraphics rat_race_epilogue_bg_map_superb;
extern struct CompressedGraphics rat_race_epilogue_bg_map_ok;
extern struct CompressedGraphics rat_race_epilogue_bg_map_try_again;
extern Palette epilogue_rat_race_bg_pal[];

extern struct CompressedGraphics remix_1_epilogue_bg_tiles;
extern struct CompressedGraphics remix_1_epilogue_bg_map_superb;
extern struct CompressedGraphics remix_1_epilogue_bg_map_ok;
extern struct CompressedGraphics remix_1_epilogue_bg_map_try_again;
extern Palette epilogue_remix1_bg_pal[];

extern struct CompressedGraphics remix_2_epilogue_bg_tiles;
extern struct CompressedGraphics remix_2_epilogue_bg_map_superb;
extern struct CompressedGraphics remix_2_epilogue_bg_map_ok;
extern struct CompressedGraphics remix_2_epilogue_bg_map_try_again;
extern Palette epilogue_remix2_bg_pal[];

extern struct CompressedGraphics remix_3_epilogue_bg_tiles;
extern struct CompressedGraphics remix_3_epilogue_bg_map_superb;
extern struct CompressedGraphics remix_3_epilogue_bg_map_ok;
extern struct CompressedGraphics remix_3_epilogue_bg_map_try_again;
extern Palette epilogue_remix3_bg_pal[];

extern struct CompressedGraphics remix_4_epilogue_bg_tiles;
extern struct CompressedGraphics remix_4_epilogue_bg_map_superb;
extern struct CompressedGraphics remix_4_epilogue_bg_map_ok;
extern struct CompressedGraphics remix_4_epilogue_bg_map_try_again;
extern Palette epilogue_remix4_bg_pal[];

extern struct CompressedGraphics remix_5_epilogue_bg_tiles;
extern struct CompressedGraphics remix_5_epilogue_bg_map_superb;
extern struct CompressedGraphics remix_5_epilogue_bg_map_ok;
extern struct CompressedGraphics remix_5_epilogue_bg_map_try_again;
extern Palette epilogue_remix5_bg_pal[];

extern struct CompressedGraphics remix_6_epilogue_bg_tiles;
extern struct CompressedGraphics remix_6_epilogue_bg_map_superb;
extern struct CompressedGraphics remix_6_epilogue_bg_map_ok;
extern struct CompressedGraphics remix_6_epilogue_bg_map_try_again;
extern Palette epilogue_remix6_bg_pal[];

extern struct CompressedGraphics remix_7_epilogue_bg_tiles;
extern struct CompressedGraphics remix_7_epilogue_bg_map_superb;
extern struct CompressedGraphics remix_7_epilogue_bg_map_ok;
extern struct CompressedGraphics remix_7_epilogue_bg_map_try_again;
extern Palette epilogue_remix7_bg_pal[];

extern struct CompressedGraphics remix_8_epilogue_bg_tiles;
extern struct CompressedGraphics remix_8_epilogue_bg_map_superb;
extern struct CompressedGraphics remix_8_epilogue_bg_map_ok;
extern struct CompressedGraphics remix_8_epilogue_bg_map_try_again;
extern Palette epilogue_remix8_bg_pal[];

extern struct CompressedGraphics ninja_bodyguard_epilogue_bg_tiles;
extern struct CompressedGraphics ninja_bodyguard_epilogue_bg_map_superb;
extern struct CompressedGraphics ninja_bodyguard_epilogue_bg_map_ok;
extern struct CompressedGraphics ninja_bodyguard_epilogue_bg_map_try_again;
extern Palette epilogue_ninja_bodyguard_bg_pal[];

extern struct CompressedGraphics ninja_reincarnate_epilogue_bg_tiles;
extern struct CompressedGraphics ninja_reincarnate_epilogue_bg_map_superb;
extern struct CompressedGraphics ninja_reincarnate_epilogue_bg_map_ok;
extern struct CompressedGraphics ninja_reincarnate_epilogue_bg_map_try_again;
extern Palette epilogue_ninja_reincarnate_bg_pal[];

extern struct CompressedGraphics space_dance_epilogue_bg_tiles;
extern struct CompressedGraphics space_dance_epilogue_bg_map_superb;
extern struct CompressedGraphics space_dance_epilogue_bg_map_ok;
extern struct CompressedGraphics space_dance_epilogue_bg_map_try_again;
extern Palette epilogue_space_dance_bg_pal[];

extern struct CompressedGraphics tap_trial_epilogue_bg_tiles;
extern struct CompressedGraphics tap_trial_epilogue_bg_map_superb;
extern struct CompressedGraphics tap_trial_epilogue_bg_map_ok;
extern struct CompressedGraphics tap_trial_epilogue_bg_map_try_again;
extern Palette epilogue_tap_trial_bg_pal[];

extern struct CompressedGraphics tap_trial_2_epilogue_bg_tiles;
extern struct CompressedGraphics tap_trial_2_epilogue_bg_map_superb;
extern struct CompressedGraphics tap_trial_2_epilogue_bg_map_ok;
extern struct CompressedGraphics tap_trial_2_epilogue_bg_map_try_again;
extern Palette epilogue_tap_trial_2_bg_pal[];

extern struct CompressedGraphics toss_boys_epilogue_bg_tiles;
extern struct CompressedGraphics toss_boys_epilogue_bg_map_superb;
extern struct CompressedGraphics toss_boys_epilogue_bg_map_ok;
extern struct CompressedGraphics toss_boys_epilogue_bg_map_try_again;
extern Palette epilogue_toss_boys_bg_pal[];

extern struct CompressedGraphics toss_boys_2_epilogue_bg_tiles;
extern struct CompressedGraphics toss_boys_2_epilogue_bg_map_superb;
extern struct CompressedGraphics toss_boys_2_epilogue_bg_map_ok;
extern struct CompressedGraphics toss_boys_2_epilogue_bg_map_try_again;
extern Palette epilogue_toss_boys_2_bg_pal[];

extern struct CompressedGraphics tram_pauline_epilogue_bg_tiles;
extern struct CompressedGraphics tram_pauline_epilogue_bg_map_superb;
extern struct CompressedGraphics tram_pauline_epilogue_bg_map_ok;
extern struct CompressedGraphics tram_pauline_epilogue_bg_map_try_again;
extern Palette epilogue_tram_pauline_bg_pal[];

extern struct CompressedGraphics sick_beats_epilogue_bg_tiles;
extern struct CompressedGraphics sick_beats_epilogue_bg_map_superb;
extern struct CompressedGraphics sick_beats_epilogue_bg_map_ok;
extern struct CompressedGraphics sick_beats_epilogue_bg_map_try_again;
extern Palette epilogue_sick_beats_bg_pal[];

extern struct CompressedGraphics wizards_waltz_epilogue_bg_tiles;
extern struct CompressedGraphics wizards_waltz_epilogue_bg_map_superb;
extern struct CompressedGraphics wizards_waltz_epilogue_bg_map_ok;
extern struct CompressedGraphics wizards_waltz_epilogue_bg_map_try_again;
extern Palette epilogue_wizards_waltz_bg_pal[];

extern struct CompressedGraphics placeholder_epilogue_bg_tiles;
extern struct CompressedGraphics placeholder_epilogue_bg_map_superb;
extern struct CompressedGraphics placeholder_epilogue_bg_map_ok;
extern struct CompressedGraphics placeholder_epilogue_bg_map_try_again;
extern Palette epilogue_placeholder_bg_pal[];
