.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Long 5) - Script Entry Point

script script_drum_lesson_long_5_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_long_5_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_long_5, script_drum_lesson_long_5_entry



.section .rodata
@ Drum Lesson (Long 5) - Data

text D_08063e10
    .ascii "よくきいてマネしてね。\n"
    .ascii "好きなタイミングでどうぞ。\n"
    .ascii "演奏を止めると、\n"
    .asciz "お手本がきけるヨ！"
endtext


script D_08063e68
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    rest 6
    rest 6
return


script D_08064084
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 3
return


text D_080640d8
    .ascii "\n"
    .ascii "スネアとシンバルで\n"
    .ascii "きっちり、まとめよう！\n"
    .asciz "がんばって！\n"
endtext


script D_08064114
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
return


script D_0806433c
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 3
return


text D_0806439c
    .ascii "\n"
    .ascii "１ヵ所だけ、スネアを\n"
    .ascii "タムにかえてみるヨ。\n"
    .asciz "わかるかな？"
endtext


script D_080643d4
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_TOM
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
return


text D_080645fc
    .ascii "\n"
    .ascii "さいごにスネアをもう１つ！\n"
    .ascii "手順をよく考えてみてネ。\n"
    .asciz "がんばれ～！"
endtext


script D_08064640
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_TOM
    rest 6
    rest 6
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return



.section .script.main
@ Drum Lesson (Long 5) - Tables

struct D_08a431e0
    .word D_08064084
    .word D_08063e68
    .word s_hakushu_solo_seqData
    .word D_08063e10
endstruct

struct D_08a431f0
    .word D_0806433c
    .word D_08064114
    .word s_hakushu_solo_seqData
    .word D_080640d8
endstruct

struct D_08a43200
    .word D_0806433c
    .word D_080643d4
    .word s_warai_little_seqData
    .word D_0806439c
endstruct

struct D_08a43210
    .word D_0806433c
    .word D_08064640
    .word s_warai_seqData
    .word D_080645fc
endstruct



@ Drum Lesson (Long 5) - Main Script

script script_drum_lesson_long_5_main
    set_tempo 110
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 4
    dms_event09 1
    rest 24
    dms_event02 TRUE
    run drum_lesson_script_import_pattern, D_08a431e0
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a431f0
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a43200
    call drum_lessons_sub_08a7d7a0
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a43210
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
