.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Long 4) - Script Entry Point

script script_drum_lesson_long_4_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_long_4_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_long_4, script_drum_lesson_long_4_entry



.section .rodata
@ Drum Lesson (Long 4) - Data

text D_08062634
    .ascii "よくきいてマネしてね。\n"
    .ascii "好きなタイミングでどうぞ。\n"
    .ascii "演奏を止めると、\n"
    .asciz "お手本がきけるヨ！"
endtext


script D_0806268c
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
return


script D_08062770
    spawn_cue CUE_KICK_R
    rest 21
return


text D_08062794
    .ascii "\n"
    .ascii "シンバルとスネアで\n"
    .ascii "キメてみよう！\n"
    .asciz "できるかな？"
endtext


script D_080627c4
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


script D_080628c0
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 21
return


text D_080628f0
    .ascii "たったの１つ、音がふえるヨ。\n"
    .ascii "でも　わりと　フクザツな\n"
    .ascii "カンジに　なるんだ！\n"
    .asciz "ついてこれるかな？"
endtext


script D_08062950
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08062a64
    .ascii "\n"
    .ascii "おわりのところを\n"
    .ascii "カッコよくしてみるネ！\n"
    .asciz "がんばってみて！\n"
endtext


script D_08062aa0
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return


text D_08062be4
    .ascii "\n"
    .ascii "アクセントをつけるヨ。\n"
    .ascii "けっこうシブいかも～！\n"
    .asciz "やるしかない！！"
endtext


script D_08062c24
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 6
    rest 12
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
return



.section .script.main
@ Drum Lesson (Long 4) - Tables

struct D_08a42b88
    .word D_08062770
    .word D_0806268c
    .word s_hakushu_solo_seqData
    .word D_08062634
endstruct

struct D_08a42b98
    .word D_080628c0
    .word D_080627c4
    .word s_hakushu_solo_seqData
    .word D_08062794
endstruct

struct D_08a42ba8
    .word D_080628c0
    .word D_08062950
    .word s_warai_little_seqData
    .word D_080628f0
endstruct

struct D_08a42bb8
    .word D_080628c0
    .word D_08062aa0
    .word s_warai_seqData
    .word D_08062a64
endstruct

struct D_08a42bc8
    .word D_080628c0
    .word D_08062c24
    .word s_kansei_solo_seqData
    .word D_08062be4
endstruct



@ Drum Lesson (Long 4) - Main Script

script script_drum_lesson_long_4_main
    set_tempo 120
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 0
    dms_event09 6
    rest 24
    dms_event02 TRUE
    run drum_lesson_script_import_pattern, D_08a42b88
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42b98
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42ba8
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42bb8
    call drum_lessons_sub_08a7d7a0
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a42bc8
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
