.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Basic 2) - Script Entry Point

script script_drum_lesson_basic_2_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_basic_2_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_basic_2, script_drum_lesson_basic_2_entry



.section .rodata
@ Drum Lesson (Basic 2) - Data

text D_08061998
    .ascii "よくきいてマネしてね。\n"
    .ascii "好きなタイミングでどうぞ。\n"
    .ascii "演奏を止めると、\n"
    .asciz "お手本がきけるヨ！"
endtext


script D_080619f0
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
return


script D_08061a44
    spawn_cue CUE_KICK_R
    rest 21
return


text D_08061a68
    .ascii "\n"
    .ascii "１カ所、音が変わるヨ！\n"
    .asciz "わかるかな？"
endtext


script D_08061a90
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08061ae4
    .ascii "\n"
    .ascii "さらに１カ所、\n"
    .ascii "音が変わるヨ！\n"
    .asciz "わかるかな？"
endtext


script D_08061b10
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08061b64
    .ascii "\n"
    .ascii "こんどは１つ、\n"
    .ascii "音がふえるヨ！\n"
    .asciz "わかるかな？\n"
endtext


script D_08061b94
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08061c00
    .ascii "\n"
    .ascii "さらに１つ、\n"
    .ascii "音がふえるヨ！\n"
    .asciz "わかるかな？"
endtext


script D_08061c2c
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_KICK_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08061cb0
    .ascii "\n"
    .ascii "またまた１つ、\n"
    .ascii "音がふえるヨ！\n"
    .asciz "わかるかな？"
endtext


script D_08061cdc
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 9
return


text D_08061d18
    .ascii "今回は、バスドラムと\n"
    .ascii "スネアドラムという、\n"
    .ascii "２つのタイコを使って\n"
    .asciz "レッスンをしましょう。"
endtext


text D_08061d70
    .ascii "\n"
    .ascii "Bボタンと十\字ボタンの下、\n"
    .ascii "どちらでもバスドラムを\n"
    .asciz "たたくことができるヨ！"
endtext


text D_08061dbc
    .ascii "\n"
    .ascii "しってると思うけど\n"
    .ascii "スネアドラムはAボタンと\n"
    .asciz "十\字ボタンの左だからネ。"
endtext


text D_08061e04
    .ascii "\n"
    .ascii "では　ぼちぼち\n"
    .asciz "はじめますネ～\n"
endtext



.section .script.main
@ Drum Lesson (Basic 2) - Tables

struct D_08a42504
    .word D_08061a44
    .word D_080619f0
    .word s_hakushu_solo_seqData
    .word D_08061998
endstruct

struct D_08a42514
    .word D_08061a44
    .word D_08061a90
    .word s_hakushu_solo_seqData
    .word D_08061a68
endstruct

struct D_08a42524
    .word D_08061a44
    .word D_08061b10
    .word s_warai_little_seqData
    .word D_08061ae4
endstruct

struct D_08a42534
    .word D_08061a44
    .word D_08061b94
    .word s_warai_seqData
    .word D_08061b64
endstruct

struct D_08a42544
    .word D_08061a44
    .word D_08061c2c
    .word s_kansei_solo_seqData
    .word D_08061c00
endstruct

struct D_08a42554
    .word D_08061cdc
    .word D_08061c2c
    .word s_kansei_seqData
    .word D_08061cb0
endstruct



@ Drum Lesson (Basic 2) - Main Script

script script_drum_lesson_basic_2_main
    set_tempo 116
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 4
    dms_event09 1
    rest 24
    rest 24
    dms_event02 TRUE
    rest 24
    dms_set_dialogue_text D_08061d18
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061d70
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061dbc
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061e04
    rest 12
    dms_event15
    dms_event16
    rest 12
    rest 24
    run drum_lesson_script_import_pattern, D_08a42504
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42514
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42524
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42534
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42544
    call drum_lessons_sub_08a7d7a0
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a42554
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
