.section .rodata
.syntax unified

.include "include/gba.inc"
.include "include/beatscript_ext.inc"


@ Prologue (Quiz Show) - Script
glabel D_089ebbec
    set_game_fade_in_time 8
    load_game quiz_show_prologue_engine, 0
    run stop_all_soundplayers, 0
    rest 24
    play_sfx s_jingle_quiz_seqData
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    run func_08006d80, 0
    rest 24
    set_game_fade_in_time 16
    return

.end
