.include "include/beatscript.inc"
.include "games/rap_men/macros.inc"



.section .script.entry
@ Rap Men - Script Entry Point

script script_rap_men_entry
    set_tempo 124
    rest 24
    call script_rap_men_prologue
    set_game_fade_in_time 16
    load_rap_men
    enable_play_inputs
    start_tracking_inputs
    call script_rap_men_practice
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_rap_men, script_rap_men_entry



@ Rap Men - Script Entry Point (Skipped Practice)

script script_rap_men_skipped_practice_entry
    set_tempo 124
    set_game_fade_in_time 0
    load_rap_men
    enable_play_inputs
    start_tracking_inputs
    call script_rap_men_skipped_practice
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_rap_men_skipped_practice, script_rap_men_skipped_practice_entry



.section .script.prologue
@ Rap Men - Prologue

script script_rap_men_prologue
    set_game_fade_in_time 8
    load_game rap_men_prologue_engine, 0
    run stop_all_soundplayers
    play_sfx s_jingle_rap_seqData
    rest 24
    rest 24
    run func_08047034, 0
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    run func_08006d80, 0
    rest 24
    set_game_fade_in_time 16
return



.section .script.main
@ Rap Men - Text

text text_rap_men_sanji_desu_ka
    .asciz ".b:1‚h‚”f‚“@‚R@‚o‚lC@.b:0‚ˆ‚•‚ˆH.8:1"
endtext

text text_rap_men_oyatsu_desu_ka
    .asciz ".b:1‚h‚”f‚“@‚“‚‚‚ƒ‚‹@‚”‚‰‚‚…C@.b:0‚ˆ‚•‚ˆH.8:1"
endtext

text text_rap_men_honto_desu_ka
    .asciz ".b:1‚l‚‚™‚‚‚…@‚“‚C@.b:0‚ˆ‚•‚ˆH.8:1"
endtext

text text_rap_men_wakarimasu_ka
    .asciz ".b:1‚x‚‚•@‚‡‚…‚”@‚‰‚”@‚‚‚—C@.b:0‚ˆ‚•‚ˆH.8:1"
endtext

text text_rap_men_oishii_kamo_ne
    .asciz ".9:1‚s‚‚“‚”‚™@‚“‚‚‚ƒ‚‹‚“C@.9:0‚™‚@‚†‚…‚…‚Œ@‚‚…H.8:1"
endtext

text text_rap_men_herushii_kamo_ne
    .asciz ".9:1‚g‚…‚‚Œ‚”‚ˆ‚™@‚“‚‚‚ƒ‚‹‚“C@.9:0‚™‚@‚†‚…‚…‚Œ@‚‚…H.8:1"
endtext

text text_rap_men_ore_no_sei_kamo_ne
    .asciz ".9:1‚l‚‰‚‡‚ˆ‚”f‚–‚…@‚‚‚…‚…‚@‚•‚“C@.9:0‚™‚@‚†‚…‚…‚Œ@‚‚…H.8:1"
endtext

text text_rap_men_sore_mo_sou_kamo_ne
    .asciz ".9:1‚s‚ˆ‚‚”f‚“@‚ˆ‚‚—@‚‰‚”@‚‚‚…C@.9:0‚™‚@‚†‚…‚…‚Œ@‚‚…H.8:1"
endtext

text text_rap_men_tanoshii_kamo_ne
    .asciz ".9:1‚g‚‚–‚‰‚f@‚†‚•‚C@.9:0‚™‚@‚†‚…‚…‚Œ@‚‚…H.8:1"
endtext

text text_rap_men_oyatsu_wa_saikou
    .asciz ".a:1‚r‚‚‚ƒ‚‹‚‰‚‚‡@‚‰‚“@.a:0‚“‚@‚`‚v‚d‚r‚n‚l‚dI.8:1"
endtext

text text_rap_men_kibun_wa_saikou
    .asciz ".a:1‚h@‚†‚…‚…‚Œ@.a:0‚“‚@‚`‚v‚d‚r‚n‚l‚dI.8:1"
endtext

text text_rap_men_ore_tte_saikou
    .asciz ".a:1‚v‚…@‚‚’‚…@.a:0‚“‚@‚`‚v‚d‚r‚n‚l‚dI.8:1"
endtext

text text_rap_men_kimi_tte_saikou
    .asciz ".a:1‚x‚‚•@‚‚’‚…@.a:0‚“‚@‚`‚v‚d‚r‚n‚l‚dI.8:0"
endtext

text text_rap_men_oyatsu_ga_nai_yo
    .asciz ".a:1‚v‚‚‰‚”@‚@‚“‚…‚ƒC@‚v‚…@.a:0‚k‚n‚r‚s@‚r‚n‚l‚dI.8:1"
endtext

text text_rap_men_ore_shiranai_yo
    .asciz ".a:1‚f‚•‚…‚“‚“@‚‰‚”f‚“@‚ˆ‚‚—@‚—‚…@.a:0‚k‚n‚r‚s@‚r‚n‚l‚dI.8:1"
endtext



@ Rap Men - Marking Criteria

struct rap_men_marking_criteria_0
    /* Positive Remark */     .word D_0805e938
    /* Negative Remark */     .word D_0805e914
    /* Flags */               .hword CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES
    /* Pos: Required Hits */  .hword 0xCC @ 80%
    /* Neg: Minimum Hits */   .hword 0x66 @ 40%
    /* Neg: Maximum Misses */ .hword 0x33 @ 20%
endstruct

struct rap_men_marking_criteria_1
    /* Positive Remark */     .word D_0805e988
    /* Negative Remark */     .word D_0805e960
    /* Flags */               .hword CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES
    /* Pos: Required Hits */  .hword 0xCC @ 80%
    /* Neg: Minimum Hits */   .hword 0x66 @ 40%
    /* Neg: Maximum Misses */ .hword 0x33 @ 20%
endstruct

struct rap_men_marking_criteria_2
    /* Positive Remark */     .word D_0805e9d8
    /* Negative Remark */     .word D_0805e9ac
    /* Flags */               .hword CHECK_AVERAGE_HITS | CHECK_AVERAGE_MISSES
    /* Pos: Required Hits */  .hword 0xCC @ 80%
    /* Neg: Minimum Hits */   .hword 0x66 @ 40%
    /* Neg: Maximum Misses */ .hword 0x33 @ 20%
endstruct

struct rap_men_marking_criteria
    .word rap_men_marking_criteria_0
    .word rap_men_marking_criteria_1
    .word rap_men_marking_criteria_2
    .word END_OF_CRITERIA
endstruct



@ Rap Men - Main Script

script script_rap_men_main
    set_results_header D_0805ea04
    import_marking_criteria rap_men_marking_criteria
    run gameplay_set_mercy_count, 1
    start_tracking_inputs
    start_perfect_campaign
    print_text_f D_0805ea18
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    clear_text_f
    play_music s_rap_bgm_seqData
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    rap_men_enable_tutorial FALSE
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 0
    print_text_f text_rap_men_sanji_desu_ka
    play_sfx s_rap_15ji_desuka_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 0
    print_text_f text_rap_men_oyatsu_desu_ka
    play_sfx s_rap_oyatu_desuka_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 0
    print_text_f text_rap_men_sanji_desu_ka
    play_sfx s_rap_15ji_desuka_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 8
    rest 8
    play_sfx s_rap_honto_desuka_seqData
    rap_men_animate_rapper ANIM_HONTO
    rest 8
    print_text_f text_rap_men_honto_desu_ka
    set_marking_criteria 0
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    play_sfx_vol s_rap_oyatu_desuka_seqData, 160
    rest 24
    run stop_sound, s_rap_oyatu_desuka_seqData
    beat_anim
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    play_sfx_vol s_rap_oyatu_desuka_seqData, 160
    rest 24
    run stop_sound, s_rap_oyatu_desuka_seqData
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 1
    print_text_f text_rap_men_oishii_kamo_ne
    play_sfx s_rap_oisi_kamone_seqData
    rap_men_animate_rapper ANIM_HONTO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    clear_text_f
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    play_sfx_vol s_rap_oyatu_desuka_seqData, 160
    rest 24
    run stop_sound, s_rap_oyatu_desuka_seqData
    beat_anim
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    play_sfx_vol s_rap_oyatu_desuka_seqData, 160
    rest 24
    run stop_sound, s_rap_oyatu_desuka_seqData
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 1
    print_text_f text_rap_men_herushii_kamo_ne
    play_sfx s_rap_herusi_kamone_seqData
    rap_men_animate_rapper ANIM_HONTO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    clear_text_f
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    play_sfx_vol s_rap_oyatu_desuka_seqData, 160
    rest 24
    run stop_sound, s_rap_oyatu_desuka_seqData
    beat_anim
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    play_sfx_vol s_rap_oyatu_desuka_seqData, 160
    rest 24
    run stop_sound, s_rap_oyatu_desuka_seqData
    beat_anim
    rest 12
    rest 6
    play_sfx_vol s_rap_oyatu_desuka_seqData, 160
    rest 6
    rap_men_animate_rapper ANIM_DESUKA
    play_sfx_vol s_rap_oyatu_desuka_seqData, 160
    rest 24
    run stop_sound, s_rap_oyatu_desuka_seqData
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 0
    print_text_f text_rap_men_oyatsu_desu_ka
    play_sfx s_rap_oyatu_desuka_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 1
    print_text_f text_rap_men_oishii_kamo_ne
    play_sfx s_rap_oisi_kamone_seqData
    rap_men_animate_rapper ANIM_HONTO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    clear_text_f
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 8
    rest 8
    play_sfx s_rap_honto_desuka_seqData
    rap_men_animate_rapper ANIM_HONTO
    rest 8
    print_text_f text_rap_men_honto_desu_ka
    set_marking_criteria 0
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 12
    rest 6
    play_sfx s_rap_herusi_kamone_seqData
    rest 6
    set_marking_criteria 1
    print_text_f text_rap_men_herushii_kamo_ne
    play_sfx s_rap_herusi_kamone_seqData
    rap_men_animate_rapper ANIM_HONTO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    clear_text_f
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_men_oyatsu_wa_saikou
    play_sfx s_rap_oyatuha_saiko_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    spawn_cue CUE_UUN
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_men_kibun_wa_saikou
    play_sfx s_rap_kibunha_saiko_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    spawn_cue CUE_UUN
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_men_ore_tte_saikou
    play_sfx s_rap_orette_saiko_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    spawn_cue CUE_UUN
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 8
    rest 8
    play_sfx s_rap_honto_desuka_seqData
    rap_men_animate_rapper ANIM_HONTO
    rest 8
    print_text_f text_rap_men_honto_desu_ka
    set_marking_criteria 0
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_men_kimi_tte_saikou
    play_sfx s_rap_kimitte_saiko_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    spawn_cue CUE_UUN
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_men_kimi_tte_saikou
    play_sfx s_rap_kimitte_saiko_seqData
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_SAIKO
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    spawn_cue CUE_UUN
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_men_oyatsu_ga_nai_yo
    play_sfx s_rap_oyatuga_naiyo_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    spawn_cue CUE_UUN
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 1
    print_text_f text_rap_men_ore_no_sei_kamo_ne
    play_sfx s_rap_orenosei_kamone_seqData
    rap_men_animate_rapper ANIM_HONTO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    clear_text_f
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 2
    print_text_f text_rap_men_ore_shiranai_yo
    play_sfx s_rap_oresira_naiyo_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    spawn_cue CUE_UUN
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    set_marking_criteria 1
    print_text_f text_rap_men_sore_mo_sou_kamo_ne
    play_sfx s_rap_soremoso_kamone_seqData
    rap_men_animate_rapper ANIM_HONTO
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    clear_text_f
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    spawn_cue CUE_UN
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    play_sfx s_rap_yeah_seqData
    rap_men_animate_rapper ANIM_KAMONE
    rest 24
    beat_anim
    rest 24
    rest 24
    print_text_f D_0805ea34
    stop_tracking_perfect_campaign
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    mod_music_volume 0, 240
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    disable_pause_menu
    rest 24
return


script script_rap_men_practice
    set_tempo 180
    set_music_volume 256
    stop_tracking_inputs
    rap_men_enable_tutorial TRUE
    rest 24
    enable_pause_menu
    rest 24
    rest 24
    rest 24
    run gameplay_display_skip_icon, 2
    run gameplay_set_tutorial scene_rap_men_skipped_practice
    play_music s_rap_bgm_renshu_seqData
    print_text_f D_0805ea44
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    print_text_f D_0805ea50
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    print_text_f D_0805ea6c
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    print_text_f D_0805ea84
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    print_text_f D_0805eaac
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    disable_play_inputs
    clear_text_f
    print_text_f text_rap_men_wakarimasu_ka
    play_sfx s_rap_wakari_desuka_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    play_sfx s_intro_uh_seqData
    beat_anim
    rest 24
    rest 24
    print_text_f text_rap_men_wakarimasu_ka
    play_sfx s_rap_wakari_desuka_seqData
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    rest 24
    rap_men_animate_rapper ANIM_DESUKA
    beat_anim
    rest 24
    spawn_cue CUE_UN
    rest 24
    clear_text_f
    play_sfx s_intro_uh_seqData
    beat_anim
    rest 24
    rest 24
    print_text_f D_0805eac4
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    enable_play_inputs
    run gameplay_reset_loop_counter
    loop_start
        run beatscript_disable_loops
        switch_loop_counter
            case 0
                print_text_f D_0805ead0
                break
            case 1
                print_text_f D_0805eae8
                break
            case 2
                print_text_f D_0805eaf8
                break
            default
                print_text_f D_0805eb14
                break
        end_switch
        beat_anim
        rest 24
        rest 24
        beat_anim
        rest 24
        rest 24
        beat_anim
        rest 24
        rest 24
        beat_anim
        rest 24
        rest 24
        clear_text_f
        print_text_f text_rap_men_wakarimasu_ka
        play_sfx s_rap_wakari_desuka_seqData
        rap_men_animate_rapper ANIM_DESUKA
        beat_anim
        rest 24
        rest 24
        rap_men_animate_rapper ANIM_DESUKA
        beat_anim
        rest 24
        rest 24
        rap_men_animate_rapper ANIM_DESUKA
        beat_anim
        rest 24
        spawn_cue CUE_UN
        rest 24
        clear_text_f
        play_sfx s_intro_uh_seqData
        beat_anim
        rest 24
        rest 24
        print_text_f text_rap_men_wakarimasu_ka
        play_sfx s_rap_wakari_desuka_seqData
        rap_men_animate_rapper ANIM_DESUKA
        beat_anim
        rest 24
        rest 24
        rap_men_animate_rapper ANIM_DESUKA
        beat_anim
        rest 24
        rest 24
        rap_men_animate_rapper ANIM_DESUKA
        beat_anim
        rest 24
        spawn_cue CUE_UN
        rest 24
        clear_text_f
        play_sfx s_intro_uh_seqData
        beat_anim
        rest 24
        rest 24
        print_text_f text_rap_men_wakarimasu_ka
        play_sfx s_rap_wakari_desuka_seqData
        rap_men_animate_rapper ANIM_DESUKA
        beat_anim
        rest 24
        rest 24
        rap_men_animate_rapper ANIM_DESUKA
        beat_anim
        rest 24
        rest 24
        rap_men_animate_rapper ANIM_DESUKA
        beat_anim
        rest 24
        spawn_cue CUE_UN
        rest 24
        clear_text_f
        play_sfx s_intro_uh_seqData
        beat_anim
        rest 24
        rest 24
        run gameplay_increment_loop_counter
    loop_end
    print_text_f D_0805eb34
    beat_anim
    rest 24
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    print_text_f D_0805eb3c
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    print_text_f D_0805eb6c
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    run gameplay_reset_loop_counter
    loop_start
        run beatscript_disable_loops
        switch_loop_counter
            case 0
                print_text_f D_0805eb94
                break
            case 1
                print_text_f D_0805ebac
                break
            case 2
                print_text_f D_0805eaf8
                break
            default
                print_text_f D_0805eb14
                break
        end_switch
        beat_anim
        rest 24
        rest 24
        beat_anim
        rest 24
        rest 24
        beat_anim
        rest 24
        rest 24
        beat_anim
        rest 24
        rest 24
        clear_text_f
        print_text_f text_rap_men_tanoshii_kamo_ne
        play_sfx s_rap_tanosi_kamone_seqData
        rap_men_animate_rapper ANIM_HONTO
        beat_anim
        rest 24
        rest 24
        rap_men_animate_rapper ANIM_DESUKA
        beat_anim
        rest 24
        rest 24
        clear_text_f
        spawn_cue CUE_UN
        beat_anim
        rest 24
        play_sfx s_intro_uh_seqData
        rest 24
        spawn_cue CUE_UN
        beat_anim
        rest 24
        play_sfx s_intro_uh_seqData
        rest 24
        print_text_f text_rap_men_tanoshii_kamo_ne
        play_sfx s_rap_tanosi_kamone_seqData
        rap_men_animate_rapper ANIM_HONTO
        beat_anim
        rest 24
        rest 24
        rap_men_animate_rapper ANIM_DESUKA
        beat_anim
        rest 24
        rest 24
        clear_text_f
        spawn_cue CUE_UN
        beat_anim
        rest 24
        play_sfx s_intro_uh_seqData
        rest 24
        spawn_cue CUE_UN
        beat_anim
        rest 24
        play_sfx s_intro_uh_seqData
        rest 24
        print_text_f text_rap_men_tanoshii_kamo_ne
        play_sfx s_rap_tanosi_kamone_seqData
        rap_men_animate_rapper ANIM_HONTO
        beat_anim
        rest 24
        rest 24
        rap_men_animate_rapper ANIM_DESUKA
        beat_anim
        rest 24
        rest 24
        clear_text_f
        spawn_cue CUE_UN
        beat_anim
        rest 24
        play_sfx s_intro_uh_seqData
        rest 24
        spawn_cue CUE_UN
        beat_anim
        rest 24
        play_sfx s_intro_uh_seqData
        rest 24
        run gameplay_increment_loop_counter
    loop_end
    print_text_f D_0805eb34
    beat_anim
    rest 24
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    print_text_f D_0805ebc4
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    run gameplay_reset_loop_counter
    loop_start
        run beatscript_disable_loops
            switch_loop_counter
            case 0
                print_text_f D_0805ebf4
                break
            case 1
                print_text_f D_0805ec0c
                break
            case 2
                print_text_f D_0805eaf8
                break
            default
                print_text_f D_0805eb14
                break
        end_switch
        beat_anim
        rest 24
        rest 24
        beat_anim
        rest 24
        rest 24
        beat_anim
        rest 24
        rest 24
        beat_anim
        rest 24
        rest 24
        clear_text_f
        print_text_f text_rap_men_kimi_tte_saikou
        play_sfx s_rap_kimitte_saiko_seqData
        rap_men_animate_rapper ANIM_SAIKO
        beat_anim
        rest 24
        rest 24
        rap_men_animate_rapper ANIM_SAIKO
        beat_anim
        rest 24
        spawn_cue CUE_UN
        rest 24
        play_sfx s_intro_uh_seqData
        clear_text_f
        spawn_cue CUE_UUN
        beat_anim
        rest 24
        play_sfx s_intro_uh_seqData
        rest 24
        beat_anim
        rest 24
        rest 24
        print_text_f text_rap_men_kimi_tte_saikou
        play_sfx s_rap_kimitte_saiko_seqData
        rap_men_animate_rapper ANIM_SAIKO
        beat_anim
        rest 24
        rest 24
        rap_men_animate_rapper ANIM_SAIKO
        beat_anim
        rest 24
        spawn_cue CUE_UN
        rest 24
        play_sfx s_intro_uh_seqData
        clear_text_f
        spawn_cue CUE_UUN
        beat_anim
        rest 24
        play_sfx s_intro_uh_seqData
        rest 24
        beat_anim
        rest 24
        rest 24
        print_text_f text_rap_men_kimi_tte_saikou
        play_sfx s_rap_kimitte_saiko_seqData
        rap_men_animate_rapper ANIM_SAIKO
        beat_anim
        rest 24
        rest 24
        rap_men_animate_rapper ANIM_SAIKO
        beat_anim
        rest 24
        spawn_cue CUE_UN
        rest 24
        play_sfx s_intro_uh_seqData
        clear_text_f
        spawn_cue CUE_UUN
        beat_anim
        rest 24
        play_sfx s_intro_uh_seqData
        rest 24
        beat_anim
        rest 24
        rest 24
        run gameplay_increment_loop_counter
    loop_end
    run gameplay_set_tutorial NULL
    print_text_f D_0805ec24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    beat_anim
    rest 24
    rest 24
    clear_text_f
    beat_anim
    rest 24
    rest 24
    goto script_rap_men_main


script script_rap_men_skipped_practice
    set_tempo 180
    set_music_volume 256
    rap_men_enable_tutorial FALSE
    rest 24
    enable_pause_menu
    rest 24
    play_music s_rap_bgm_renshu_seqData
    goto script_rap_men_main

.end
