// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "karate_man_anim_cells.inc.c"

struct Animation anim_karate_joe_stand[] = {
    /* 000 */ { karate_man_cel000, 24 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_karate_object[] = {
    /* 000 */ { karate_man_cel035, 40 },
    /* 001 */ { karate_man_cel039, 40 },
    /* 002 */ { karate_man_cel037, 40 },
    /* 003 */ { karate_man_cel038, 40 },
    /* 004 */ { karate_man_cel036, 40 },
    /* 005 */ END_ANIMATION,
};

struct Animation anim_karate_object_shadow[] = {
    /* 000 */ { karate_man_cel040, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_karate_object_shards[] = {
    /* 000 */ { karate_man_cel041, 40 },
    /* 001 */ { karate_man_cel042, 40 },
    /* 002 */ END_ANIMATION,
};

struct Animation anim_karate_joe_punch_high[] = {
    /* 000 */ { karate_man_cel020, 1 },
    /* 001 */ { karate_man_cel019, 3 },
    /* 002 */ { karate_man_cel021, 2 },
    /* 003 */ { karate_man_cel022, 2 },
    /* 004 */ { karate_man_cel023, 2 },
    /* 005 */ { karate_man_cel002, 1 },
    /* 006 */ { karate_man_cel001, 1 },
    /* 007 */ { karate_man_cel000, 15 },
    /* 008 */ END_ANIMATION,
};

struct Animation anim_karate_joe_beat[] = {
    /* 000 */ { karate_man_cel002, 3 },
    /* 001 */ { karate_man_cel001, 3 },
    /* 002 */ { karate_man_cel000, 24 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_karate_hit_effect[] = {
    /* 000 */ { karate_man_cel043, 2 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_karate_joe_sad[] = {
    /* 000 */ { karate_man_cel027, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_karate_flow_meter[] = {
    /* 000 */ { karate_man_cel044, 40 },
    /* 001 */ { karate_man_cel045, 40 },
    /* 002 */ { karate_man_cel046, 40 },
    /* 003 */ { karate_man_cel047, 40 },
    /* 004 */ { karate_man_cel048, 40 },
    /* 005 */ { karate_man_cel049, 40 },
    /* 006 */ END_ANIMATION,
};

struct Animation anim_karate_joe_punch_low[] = {
    /* 000 */ { karate_man_cel015, 4 },
    /* 001 */ { karate_man_cel016, 2 },
    /* 002 */ { karate_man_cel017, 2 },
    /* 003 */ { karate_man_cel018, 2 },
    /* 004 */ { karate_man_cel002, 1 },
    /* 005 */ { karate_man_cel001, 1 },
    /* 006 */ { karate_man_cel000, 40 },
    /* 007 */ END_ANIMATION,
};

struct Animation anim_karate_joe_barely[] = {
    /* 000 */ { karate_man_cel005, 3 },
    /* 001 */ { karate_man_cel004, 3 },
    /* 002 */ { karate_man_cel003, 24 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_karate_joe_miss[] = {
    /* 000 */ { karate_man_cel008, 3 },
    /* 001 */ { karate_man_cel007, 3 },
    /* 002 */ { karate_man_cel006, 24 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_karate_joe_smirk[] = {
    /* 000 */ { karate_man_cel011, 3 },
    /* 001 */ { karate_man_cel010, 3 },
    /* 002 */ { karate_man_cel009, 24 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_karate_joe_happy[] = {
    /* 000 */ { karate_man_cel014, 3 },
    /* 001 */ { karate_man_cel013, 3 },
    /* 002 */ { karate_man_cel012, 24 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_karate_joe_punch_ouch[] = {
    /* 000 */ { karate_man_cel024, 3 },
    /* 001 */ { karate_man_cel025, 2 },
    /* 002 */ { karate_man_cel026, 2 },
    /* 003 */ { karate_man_cel025, 2 },
    /* 004 */ { karate_man_cel026, 2 },
    /* 005 */ { karate_man_cel025, 2 },
    /* 006 */ { karate_man_cel026, 2 },
    /* 007 */ { karate_man_cel025, 2 },
    /* 008 */ { karate_man_cel026, 2 },
    /* 009 */ { karate_man_cel025, 2 },
    /* 010 */ { karate_man_cel026, 2 },
    /* 011 */ { karate_man_cel025, 2 },
    /* 012 */ { karate_man_cel026, 20 },
    /* 013 */ END_ANIMATION,
};

struct Animation anim_karate_flow_meter_test1[] = {
    /* 000 */ { karate_man_cel050, 4 },
    /* 001 */ { karate_man_cel051, 4 },
    /* 002 */ { karate_man_cel052, 4 },
    /* 003 */ { karate_man_cel053, 4 },
    /* 004 */ { karate_man_cel054, 4 },
    /* 005 */ { karate_man_cel055, 4 },
    /* 006 */ { karate_man_cel056, 4 },
    /* 007 */ { karate_man_cel057, 4 },
    /* 008 */ { karate_man_cel058, 4 },
    /* 009 */ { karate_man_cel059, 4 },
    /* 010 */ { karate_man_cel060, 4 },
    /* 011 */ END_ANIMATION,
};

struct Animation anim_karate_flow_meter_test2[] = {
    /* 000 */ { karate_man_cel061, 4 },
    /* 001 */ { karate_man_cel062, 4 },
    /* 002 */ { karate_man_cel063, 4 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_karate_cue_warning[] = {
    /* 000 */ { karate_man_cel065, 40 },
    /* 001 */ { karate_man_cel066, 40 },
    /* 002 */ { karate_man_cel067, 40 },
    /* 003 */ { karate_man_cel064, 40 },
    /* 004 */ { karate_man_cel075, 40 },
    /* 005 */ END_ANIMATION,
};

struct Animation anim_karate_tutorial_text_button[] = {
    /* 000 */ { karate_man_cel069, 10 },
    /* 001 */ { karate_man_cel068, 30 },
    /* 002 */ END_ANIMATION,
};

struct Animation anim_karate_tutorial_skip[] = {
    /* 000 */ { karate_man_cel070, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_karate_tutorial_counter[] = {
    /* 000 */ { karate_man_cel074, 40 },
    /* 001 */ { karate_man_cel071, 40 },
    /* 002 */ { karate_man_cel072, 40 },
    /* 003 */ { karate_man_cel073, 40 },
    /* 004 */ END_ANIMATION,
};

struct Animation anim_karate_joe_smug_high[] = {
    /* 000 */ { karate_man_cel020, 1 },
    /* 001 */ { karate_man_cel019, 3 },
    /* 002 */ { karate_man_cel021, 2 },
    /* 003 */ { karate_man_cel022, 2 },
    /* 004 */ { karate_man_cel023, 2 },
    /* 005 */ { karate_man_cel030, 1 },
    /* 006 */ { karate_man_cel029, 1 },
    /* 007 */ { karate_man_cel028, 15 },
    /* 008 */ END_ANIMATION,
};

struct Animation anim_karate_joe_smug_low[] = {
    /* 000 */ { karate_man_cel031, 4 },
    /* 001 */ { karate_man_cel032, 2 },
    /* 002 */ { karate_man_cel033, 2 },
    /* 003 */ { karate_man_cel034, 2 },
    /* 004 */ { karate_man_cel030, 1 },
    /* 005 */ { karate_man_cel029, 1 },
    /* 006 */ { karate_man_cel028, 40 },
    /* 007 */ END_ANIMATION,
};

