@ Data transfer registers, still do not care to label


.set REG_RCNT,         	IORAMBase + 0x134
.set REG_JOYCNT,    	IORAMBase + 0x140
.set REG_JOYRE,      	IORAMBase + 0x150
.set REG_JOYRE_L,    	IORAMBase + 0x150
.set REG_JOYRE_H,    	IORAMBase + 0x152
.set REG_JOYTR,      	IORAMBase + 0x154
.set REG_JOYTR_L,    	IORAMBase + 0x154
.set REG_JOYTR_H,    	IORAMBase + 0x156
.set REG_JSTAT,      	IORAMBase + 0x158
.set REG_JSTAT_L,    	IORAMBase + 0x158
.set REG_JSTAT_H,    	IORAMBase + 0x15A
