#pragma once

enum ReadingMaterialEnum {
    /* 00 */ READING_MATERIAL_WELCOME,
    /* 01 */ READING_MATERIAL_MANUAL,
    /* 02 */ READING_MATERIAL_CAFE,
    /* 03 */ READING_MATERIAL_RHYTHM_TWEEZERS,
    /* 04 */ READING_MATERIAL_NIGHT_WALK,
    /* 05 */ READING_MATERIAL_SPACEBALL,
    /* 06 */ READING_MATERIAL_MECHANICAL_HORSE,
    /* 07 */ READING_MATERIAL_MARCHING_ORDERS,
    /* 08 */ READING_MATERIAL_RAP_MEN,
    /* 09 */ READING_MATERIAL_BON_ODORI,
    /* 10 */ READING_MATERIAL_REMIX3,
    /* 11 */ READING_MATERIAL_REMIX5,
    /* 12 */ READING_MATERIAL_REMIX8,
    /* 13 */ READING_MATERIAL_NINJA_BODYGUARD,
    /* 14 */ READING_MATERIAL_TOSS_BOYS,
    /* 15 */ READING_MATERIAL_FAN_MAIL,
    /* 16 */ READING_MATERIAL_RHYTHM_FORMULA,
    /* 17 */ READING_MATERIAL_RHYTHM_DIAGNOSIS,
    /* 18 */ READING_MATERIAL_RHYTHM_POEM,
    /* 19 */ READING_MATERIAL_RHYTHM_HAIKU,
    /* -- */ TOTAL_BASE_READING_MATERIALS,
    /* <insert new reading materials here> */
    /* -- */ TOTAL_EXTRA_READING_MATERIALS = (READING_MATERIAL_RHYTHM_HAIKU + 1 - TOTAL_BASE_READING_MATERIALS),
    /* -- */ TOTAL_READING_MATERIALS = TOTAL_BASE_READING_MATERIALS + TOTAL_EXTRA_READING_MATERIALS
};