.include "include/beatscript.inc"
.include "games/drum_live/macros.inc"

load_drum_live_labels



.section .script.main
@ Drum Girls LIVE - Night Walk

script script_drum_girls_night_walk
    set_tempo 127
    set_music_volume 200
    mute_music_track (MIDI_TRACK_3 | MIDI_TRACK_6)
    dml_clear_input_def
    dml_define_cool_inputs 0, (A_BUTTON | B_BUTTON | DPAD_LEFT | DPAD_DOWN)
    dml_define_cool_inputs 1, (A_BUTTON | B_BUTTON | DPAD_LEFT | DPAD_DOWN)
    run drum_girls_night_walk_start_crowd_sfx
    dml_set_disable_excitement TRUE
    dml_set_enable_boredom FALSE
    rest 24
    rest 24
    rest 24
    rest 24
    run drum_girls_night_walk_play_count_in, 0
    rest 24
    rest 24
    run drum_girls_night_walk_play_count_in, 0
    rest 24
    rest 24
    run drum_girls_night_walk_play_count_in, 0
    rest 24
    run drum_girls_night_walk_play_count_in, 0
    rest 24
    run drum_girls_night_walk_play_count_in, 0
    rest 24
    run drum_girls_night_walk_play_count_in, 0
    dml_event06 TRUE
    call drum_live_pat00
    play_music s_4beat_bgm_seqData
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    run drum_girls_night_walk_stop_crowd_sfx
    call drum_live_pat00
    dml_set_disable_excitement FALSE
    dml_set_enable_boredom TRUE
    dml_event06 FALSE
    call drum_live_pat08
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    dml_event06 TRUE
    call drum_live_pat08
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat10
    dml_set_guitarist_next_state 0x3, 1
    call drum_live_pat10
    dml_set_guitarist_next_state 0x3, 2
    call drum_live_pat10
    dml_set_guitarist_next_state 0x3, 0
    dml_event06 FALSE
    call drum_live_pat08
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    dml_set_disable_excitement TRUE
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    dml_set_enable_boredom FALSE
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    dml_event07
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
return


.end
