.include "include/beatscript.inc"
.include "games/drum_live/macros.inc"

load_drum_live_labels



.section .script.main
@ Drum Boys LIVE - WISH Kimi wo Matenakute

script script_drum_boys_wish
    set_tempo 204
    set_music_volume 200
    mute_music_track (MIDI_TRACK_5 | MIDI_TRACK_6)
    run drum_boys_wish_start_crowd_sfx
    rest 24
    rest 24
    rest 24
    rest 24
    run drum_boys_wish_play_count_in, 0
    rest 24
    rest 24
    run drum_boys_wish_play_count_in, 0
    rest 24
    rest 24
    dml_clear_input_def
    dml_define_cool_inputs 0, (A_BUTTON | B_BUTTON | DPAD_LEFT | DPAD_DOWN)
    dml_define_cool_inputs 1, (A_BUTTON | B_BUTTON | DPAD_LEFT | DPAD_DOWN)
    run drum_boys_wish_play_count_in, 0
    call drum_live_pat01
    run drum_boys_wish_play_count_in, 0
    call drum_live_pat01
    run drum_boys_wish_play_count_in, 0
    call drum_live_pat01
    run drum_boys_wish_play_count_in, 0
    dml_set_disable_excitement FALSE
    dml_event06 TRUE
    dml_set_guitarist_next_state 0x3, 1
    call drum_live_pat08
    play_music s_wish_bgm_seqData
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    dml_set_guitarist_next_state 0x3, 4
    call drum_live_pat01
    dml_set_guitarist_next_state 0x3, 0
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    call drum_live_pat00
    call drum_live_pat01
    run drum_boys_wish_stop_crowd_sfx
    dml_set_enable_boredom TRUE
    dml_event06 TRUE
    dml_set_guitarist_next_state 0x3, 1
    call drum_live_pat11
    call drum_live_pat11
    call drum_live_pat11
    call drum_live_pat11
    call drum_live_pat11
    call drum_live_pat11
    call drum_live_pat11
    call drum_live_pat11
    dml_set_guitarist_next_state 0x3, 2
    call drum_live_pat08
    dml_set_guitarist_next_state 0x3, 0
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat08
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    dml_event06 FALSE
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat15
    call drum_live_pat15
    call drum_live_pat08
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    dml_event06 TRUE
    dml_set_guitarist_next_state 0x1, 1
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    dml_set_guitarist_next_state 0x2, 1
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    dml_set_guitarist_next_state 0x1, 4
    call drum_live_pat10
    dml_set_guitarist_next_state 0x1, 0
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat00
    dml_set_guitarist_next_state 0x2, 4
    call drum_live_pat10
    dml_set_guitarist_next_state 0x2, 0
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat12
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat12
    call drum_live_pat00
    call drum_live_pat11
    call drum_live_pat11
    dml_event06 FALSE
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    dml_set_guitarist_next_state 0x3, 1
    call drum_live_pat10
    dml_event06 TRUE
    call drum_live_pat03
    dml_event06 FALSE
    call drum_live_pat10
    dml_set_guitarist_next_state 0x3, 0
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat08
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat13
    call drum_live_pat13
    call drum_live_pat13
    call drum_live_pat13
    call drum_live_pat13
    call drum_live_pat13
    call drum_live_pat13
    call drum_live_pat13
    dml_event06 FALSE
    call drum_live_pat08
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    dml_set_guitarist_next_state 0x3, 1
    call drum_live_pat10
    dml_event06 TRUE
    call drum_live_pat03
    dml_event06 FALSE
    call drum_live_pat10
    dml_set_guitarist_next_state 0x3, 0
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat08
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    dml_event06 TRUE
    dml_set_guitarist_next_state 0x3, 1
    call drum_live_pat08
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    dml_set_guitarist_next_state 0x3, 4
    call drum_live_pat10
    dml_set_guitarist_next_state 0x3, 0
    call drum_live_pat10
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    call drum_live_pat00
    dml_set_disable_excitement TRUE
    call drum_live_pat08
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat10
    call drum_live_pat12
    call drum_live_pat00
    dml_set_guitarist_next_state 0x3, 1
    call drum_live_pat08
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    run drum_boys_wish_play_count_in, 80
    rest 24
    run drum_boys_wish_play_count_in, 80
    rest 24
    run drum_boys_wish_play_count_in, 80
    rest 24
    run drum_boys_wish_play_count_in, 80
    dml_event06 FALSE
    dml_set_guitarist_next_state 0x3, 2
    call drum_live_pat08
    dml_set_enable_boredom FALSE
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
    rest 24
return


.end
